var KeyMapping = [
    {"keyCode":"65","functionType":"Singlekey","value":"A","hid":4,"translate":"A","code":"KeyA"},
    {"keyCode":"66","functionType":"Singlekey","value":"B","hid":5,"translate":"B","code":"KeyB"},
    {"keyCode":"67","functionType":"Singlekey","value":"C","hid":6,"translate":"C","code":"KeyC"},
    {"keyCode":"68","functionType":"Singlekey","value":"D","hid":7,"translate":"D","code":"KeyD"},
    {"keyCode":"69","functionType":"Singlekey","value":"E","hid":8,"translate":"E","code":"KeyE"},
    {"keyCode":"70","functionType":"Singlekey","value":"F","hid":9,"translate":"F","code":"KeyF"},
    {"keyCode":"71","functionType":"Singlekey","value":"G","hid":10,"translate":"G","code":"KeyG"},
    {"keyCode":"72","functionType":"Singlekey","value":"H","hid":11,"translate":"H","code":"KeyH"},
    {"keyCode":"73","functionType":"Singlekey","value":"I","hid":12,"translate":"I","code":"KeyI"},
    {"keyCode":"74","functionType":"Singlekey","value":"J","hid":13,"translate":"J","code":"KeyJ"},
    {"keyCode":"75","functionType":"Singlekey","value":"K","hid":14,"translate":"K","code":"KeyK"},
    {"keyCode":"76","functionType":"Singlekey","value":"L","hid":15,"translate":"L","code":"KeyL"},
    {"keyCode":"77","functionType":"Singlekey","value":"M","hid":16,"translate":"M","code":"KeyM"},
    {"keyCode":"78","functionType":"Singlekey","value":"N","hid":17,"translate":"N","code":"KeyN"},
    {"keyCode":"79","functionType":"Singlekey","value":"O","hid":18,"translate":"O","code":"KeyO"},
    {"keyCode":"80","functionType":"Singlekey","value":"P","hid":19,"translate":"P","code":"KeyP"},
    {"keyCode":"81","functionType":"Singlekey","value":"Q","hid":20,"translate":"Q","code":"KeyQ"},
    {"keyCode":"82","functionType":"Singlekey","value":"R","hid":21,"translate":"R","code":"KeyR"},
    {"keyCode":"83","functionType":"Singlekey","value":"S","hid":22,"translate":"S","code":"KeyS"},
    {"keyCode":"84","functionType":"Singlekey","value":"T","hid":23,"translate":"T","code":"KeyT"},
    {"keyCode":"85","functionType":"Singlekey","value":"U","hid":24,"translate":"U","code":"KeyU"},
    {"keyCode":"86","functionType":"Singlekey","value":"V","hid":25,"translate":"V","code":"KeyV"},
    {"keyCode":"87","functionType":"Singlekey","value":"W","hid":26,"translate":"W","code":"KeyW"},
    {"keyCode":"88","functionType":"Singlekey","value":"X","hid":27,"translate":"X","code":"KeyX"},
    {"keyCode":"89","functionType":"Singlekey","value":"Y","hid":28,"translate":"Y","code":"KeyY"},
    {"keyCode":"90","functionType":"Singlekey","value":"Z","hid":29,"translate":"Z","code":"KeyZ"},
    {"keyCode":"48","functionType":"Singlekey","value":"0","hid":39,"translate":"0","code":"Digit0"},
    {"keyCode":"49","functionType":"Singlekey","value":"1","hid":30,"translate":"1","code":"Digit1"},
    {"keyCode":"50","functionType":"Singlekey","value":"2","hid":31,"translate":"2","code":"Digit2"},
    {"keyCode":"51","functionType":"Singlekey","value":"3","hid":32,"translate":"3","code":"Digit3"},
    {"keyCode":"52","functionType":"Singlekey","value":"4","hid":33,"translate":"4","code":"Digit4"},
    {"keyCode":"53","functionType":"Singlekey","value":"5","hid":34,"translate":"5","code":"Digit5"},
    {"keyCode":"54","functionType":"Singlekey","value":"6","hid":35,"translate":"6","code":"Digit6"},
    {"keyCode":"55","functionType":"Singlekey","value":"7","hid":36,"translate":"7","code":"Digit7"},
    {"keyCode":"56","functionType":"Singlekey","value":"8","hid":37,"translate":"8","code":"Digit8"},
    {"keyCode":"57","functionType":"Singlekey","value":"9","hid":38,"translate":"9","code":"Digit9"},
    {"keyCode":"8","functionType":"Singlekey","value":"Backspace","hid":42,"translate":"Backspace","code":"Backspace"},
    {"keyCode":"9","functionType":"Singlekey","value":"Tab","hid":43,"translate":"Tab","code":"Tab"},
    {"keyCode":"144","functionType":"Singlekey","value":"Num Lock","hid":83,"translate":"Num Lock","code":"NumLock"},
    {"keyCode":"13","functionType":"Singlekey","value":"Enter","hid":40,"translate":"Enter","code":"Enter"},
    {"keyCode":"16","functionType":"Singlekey","value":"Shift","hid":225,"Modifier":0x02,"translate":"Shift","code":"ShiftRight"},
    {"keyCode":"17","functionType":"Singlekey","value":"Ctrl","hid":224,"Modifier":0x01,"translate":"Ctrl","code":"ControlLeft"},
    {"keyCode":"18","functionType":"Singlekey","value":"Alt","hid":226,"Modifier":0x04,"translate":"Alt","code":"AltRight"},
    {"keyCode":"19","functionType":"Singlekey","value":"Break","hid":72,"translate":"Break","code":"Pause"},
    {"keyCode":"20","functionType":"Singlekey","value":"CapsLock","hid":57,"translate":"CapsLock","code":"CapsLock"},
    {"keyCode":"27","functionType":"Singlekey","value":"Esc","hid":41,"translate":"Esc","code":"Escape"},
    {"keyCode":"32","functionType":"Singlekey","value":"Space","hid":44,"translate":"Space","code":"Space"},
    {"keyCode":"33","functionType":"Singlekey","value":"PageUp","hid":75,"translate":"PageUp","code":"PageUp"},
    {"keyCode":"34","functionType":"Singlekey","value":"PageDown","hid":78,"translate":"PageDown","code":"PageDown"},
    {"keyCode":"35","functionType":"Singlekey","value":"End","hid":77,"translate":"End","code":"End"},
    {"keyCode":"36","functionType":"Singlekey","value":"Home","hid":74,"translate":"Home","code":"Home"},
    {"keyCode":"37","functionType":"Singlekey","value":"Left","hid":80,"translate":"Left","code":"ArrowLeft"},
    {"keyCode":"38","functionType":"Singlekey","value":"Up","hid":82,"translate":"Up","code":"ArrowUp"},
    {"keyCode":"39","functionType":"Singlekey","value":"Right","hid":79,"translate":"Right","code":"ArrowRight"},
    {"keyCode":"40","functionType":"Singlekey","value":"Down","hid":81,"translate":"Down","code":"ArrowDown"},
    {"keyCode":"44","functionType":"Singlekey","value":"PrintScreen","hid":"0x46","translate":"PrintScreen","code":"PrintScreen"},
    {"keyCode":"45","functionType":"Singlekey","value":"Insert","hid":73,"translate":"Insert","code":"Insert"},
    {"keyCode":"46","functionType":"Singlekey","value":"Delete","hid":76,"translate":"Delete","code":"Delete"},
    {"keyCode":"91","functionType":"Singlekey","value":"Left Win","hid":227,"Modifier":0x08,"translate":"Left Win","code":"MetaLeft"},
    {"keyCode":"92","functionType":"Singlekey","value":"Right Win","hid":231,"Modifier":0x80,"translate":"Right Win","code":"MetaRight"},
    {"keyCode":"93","functionType":"Singlekey","value":"Menu","hid":101,"translate":"Menu","code":"ContextMenu"},
    {"keyCode":"106","functionType":"Singlekey","value":"*","hid":85,"translate":"*","code":"NumpadMultiply"},
    {"keyCode":"107","functionType":"Singlekey","value":"+","hid":87,"translate":"+","code":"NumpadAdd"},
    {"keyCode":"109","functionType":"Singlekey","value":"-","hid":86,"translate":"-","code":"NumpadSubtract"},
    {"keyCode":"110","functionType":"Singlekey","value":".","hid":0x63,"translate":".","code":"NumpadDecimal"},
    {"keyCode":"111","functionType":"Singlekey","value":"/","hid":84,"translate":"/","code":"NumpadDivide"},
    {"keyCode":"112","functionType":"Singlekey","value":"F1","hid":58,"translate":"F1","code":"F1"},
    {"keyCode":"113","functionType":"Singlekey","value":"F2","hid":59,"translate":"F2","code":"F2"},
    {"keyCode":"114","functionType":"Singlekey","value":"F3","hid":60,"translate":"F3","code":"F3"},
    {"keyCode":"115","functionType":"Singlekey","value":"F4","hid":61,"translate":"F4","code":"F4"},
    {"keyCode":"116","functionType":"Singlekey","value":"F5","hid":62,"translate":"F5","code":"F5"},
    {"keyCode":"117","functionType":"Singlekey","value":"F6","hid":63,"translate":"F6","code":"F6"},
    {"keyCode":"118","functionType":"Singlekey","value":"F7","hid":64,"translate":"F7","code":"F7"},
    {"keyCode":"119","functionType":"Singlekey","value":"F8","hid":65,"translate":"F8","code":"F8"},
    {"keyCode":"120","functionType":"Singlekey","value":"F9","hid":66,"translate":"F9","code":"F9"},
    {"keyCode":"121","functionType":"Singlekey","value":"F10","hid":67,"translate":"F10","code":"F10"},
    {"keyCode":"122","functionType":"Singlekey","value":"F11","hid":68,"translate":"F11","code":"F11"},
    {"keyCode":"123","functionType":"Singlekey","value":"F12","hid":69,"translate":"F12","code":"F12"},
    {"keyCode":"145","functionType":"Singlekey","value":"Scroll Lock","hid":71,"translate":"Scroll Lock","code":"ScrollLock"},
    {"keyCode":"186","functionType":"Singlekey","value":";","hid":51,"translate":";","code":"Semicolon"},
    {"keyCode":"187","functionType":"Singlekey","value":"=","hid":46,"translate":"=","code":"Equal"},
    {"keyCode":"188","functionType":"Singlekey","value":",","hid":54,"translate":",","code":"Comma"},
    {"keyCode":"189","functionType":"Singlekey","value":"-","hid":45,"translate":"-","code":"Minus"},
    {"keyCode":"190","functionType":"Singlekey","value":"dot","hid":55,"translate":"dot","code":"Period"},
    {"keyCode":"191","functionType":"Singlekey","value":"/","hid":56,"translate":"/","code":"Slash"},
    {"keyCode":"192","functionType":"Singlekey","value":"~","hid":53,"translate":"~","code":"Backquote"},
    {"keyCode":"219","functionType":"Singlekey","value":"[","hid":47,"translate":"[","code":"BracketLeft"},
    {"keyCode":"220","functionType":"Singlekey","value":"|","hid":49,"translate":"|","code":"Backslash"},
    {"keyCode":"221","functionType":"Singlekey","value":"]","hid":48,"translate":"]","code":"BracketRight"},
    {"keyCode":"222","functionType":"Singlekey","value":"'","hid":52,"translate":"'","code":"Quote"}

]
var MediaMapping = [
    { keyCode: '1', value: 'None', "hid":0x04, hidMap: [0x00, 0x00], translate: '' },
    { keyCode: '1', value: 'Media Player', "hid":0x04, hidMap: [0x01, 0x83], translate: '' },
    { keyCode: '1', value: 'Play/Pause', "hid":0x04, hidMap: [0x00, 0xcd], translate: '' },
    { keyCode: '1', value: 'Next', "hid":0x04, hidMap: [0x00, 0xb5], translate: '' },
    { keyCode: '1', value: 'Previous', "hid":0x04, hidMap: [0x00, 0xb6], translate: '' },
    { keyCode: '1', value: 'Stop', "hid":0x04, hidMap: [0x00, 0xb7], translate: '' },
    { keyCode: '1', value: 'Mute', "hid":0x04, hidMap: [0x00, 0xe2], translate: '' },
    { keyCode: '1', value: 'Volume up', "hid":0x04, hidMap: [0x00, 0xe9], translate: '' },
    { keyCode: '1', value: 'Volume down', "hid":0x04, hidMap: [0x00, 0xea], translate: '' },
    { keyCode: '1', value: 'Next track', "hid":0x04, hidMap: [0x00, 0xb5], translate: '' },
    { keyCode: '1', value: 'Previous track', "hid":0x04, hidMap: [0x00, 0xb6], translate: '' },
]
var WindowsMapping = [
    { keyCode: '1', value: 'None', "hid":0x04, hidMap: [0x00, 0x00], translate: '' },
    { keyCode: '1', value: 'Email', "hid":0x04, hidMap: [0x01, 0x8a], translate: '' },
    { keyCode: '1', value: 'Calculator', "hid":0x04, hidMap: [0x01, 0x92], translate: '' },
    { keyCode: '1', value: 'My Computer', "hid":0x04, hidMap: [0x01, 0x94], translate: '' },
    { keyCode: '1', value: 'Explorer', "hid":0x04, hidMap: [0x01, 0x94], translate: '' },
    { keyCode: '1', value: 'WWW Home', "hid":0x04, hidMap: [0x02, 0x23], translate: '' },
    { keyCode: '1', value: 'WWW Refresh', "hid":0x04, hidMap: [0x02, 0x27], translate: '' },
    { keyCode: '1', value: 'WWW Stop', "hid":0x04, hidMap: [0x02, 0x26], translate: '' },
    { keyCode: '1', value: 'WWW Back', "hid":0x04, hidMap: [0x02, 0x24], translate: '' },
    { keyCode: '1', value: 'WWW Forward', "hid":0x04, hidMap: [0x02, 0x25], translate: '' },
    { keyCode: '1', value: 'WWW Search', "hid":0x04, hidMap: [0x02, 0x21], translate: '' },
]

var Shortcuts_WindowsMapping=[
    {"keyCode":"Shortcuts_Fun_25","functionType":"Shortcuts","value":"Email","hid":17,"translate":"Email","code":"Shortcuts_Fun_25"},
    {"keyCode":"Shortcuts_Fun_26","functionType":"Shortcuts","value":"Calculator","hid":16,"translate":"Calculator","code":"Shortcuts_Fun_26"},
    {"keyCode":"Shortcuts_Fun_27","functionType":"Shortcuts","value":"My Computer","hid":15,"translate":"My Computer","code":"Shortcuts_Fun_27"},
    {"keyCode":"Shortcuts_Fun_28","functionType":"Shortcuts","value":"Explorer","hid":15,"translate":"Explorer","code":"Shortcuts_Fun_28"},
    {"keyCode":"Shortcuts_Fun_29","functionType":"Shortcuts","value":"WWW Home","hid":8,"translate":"WWW Home","code":"Shortcuts_Fun_29"},
    {"keyCode":"Shortcuts_Fun_30","functionType":"Shortcuts","value":"WWW Refresh","hid":9,"translate":"WWW Refresh","code":"Shortcuts_Fun_30"},
    {"keyCode":"Shortcuts_Fun_31","functionType":"Shortcuts","value":"WWW Stop","hid":10,"translate":"WWW Stop","code":"Shortcuts_Fun_31"},
    {"keyCode":"Shortcuts_Fun_32","functionType":"Shortcuts","value":"WWW Back","hid":11,"translate":"WWW Back","code":"Shortcuts_Fun_32"},
    {"keyCode":"Shortcuts_Fun_33","functionType":"Shortcuts","value":"WWW Forward","hid":12,"translate":"WWW Forward","code":"Shortcuts_Fun_33"},
    {"keyCode":"Shortcuts_Fun_34","functionType":"Shortcuts","value":"WWW Search","hid":14,"translate":"WWW Search","code":"Shortcuts_Fun_34"},
]
var SupportLanguage = [
    { name: 'ENGLISH', value: 'en' },
    // {name:'繁體中文', value:"tw"},
    // {name:'简体中文', value:"cn"}
]

var AllFunctionMapping =[{"keyCode":"Multimedia_Fun_0","functionType":"Multimedia","value":"Media Player","hid":0,"translate":"Media Player","code":"Multimedia_Fun_0"},
{"keyCode":"Multimedia_Fun_1","functionType":"Multimedia","value":"Play/Pause","hid":1,"translate":"Play/Pause","code":"Multimedia_Fun_1"},
{"keyCode":"Multimedia_Fun_2","functionType":"Multimedia","value":"Next","hid":7,"translate":"Next","code":"Multimedia_Fun_2"},
{"keyCode":"Multimedia_Fun_3","functionType":"Multimedia","value":"Previous","hid":6,"translate":"Previous","code":"Multimedia_Fun_3"},
{"keyCode":"Multimedia_Fun_4","functionType":"Multimedia","value":"Stop","hid":5,"translate":"Stop","code":"Multimedia_Fun_4"},
{"keyCode":"Multimedia_Fun_5","functionType":"Multimedia","value":"Mute","hid":2,"translate":"Mute","code":"Multimedia_Fun_5"},
{"keyCode":"Multimedia_Fun_6","functionType":"Multimedia","value":"Volume up","hid":3,"translate":"Volume up","code":"Multimedia_Fun_6"},
{"keyCode":"Multimedia_Fun_7","functionType":"Multimedia","value":"Volume down","hid":4,"translate":"Volume down","code":"Multimedia_Fun_7"},
{"keyCode":"Multimedia_Fun_8","functionType":"Multimedia","value":"Next track","hid":7,"translate":"Next trac","code":"Multimedia_Fun_8"},
{"keyCode":"Multimedia_Fun_9","functionType":"Multimedia","value":"Previoustrack","hid":6,"translate":"Previoustrack","code":"Multimedia_Fun_9"},
{"keyCode":"KEYBOARD_Fun_10","functionType":"KEYBOARD","value":"Profilecycleup","hid":2,"translate":"Profilecycleup","code":"KEYBOARD_Fun_10"},
{"keyCode":"KEYBOARD_Fun_11","functionType":"KEYBOARD","value":"Profilecycledown","hid":1,"translate":"Profilecycledown","code":"KEYBOARD_Fun_11"},
{"keyCode":"KEYBOARD_Fun_12","functionType":"KEYBOARD","value":"Layercycleup","hid":4,"translate":"Layercycleup","code":"KEYBOARD_Fun_12"},
{"keyCode":"KEYBOARD_Fun_13","functionType":"KEYBOARD","value":"Layercycledown","hid":3,"translate":"Layercycledown","code":"KEYBOARD_Fun_13"},
{"keyCode":"MOUSE_Fun_14","functionType":"MOUSE","value":"Leftbutton","hid":1,"translate":"Leftbutton","code":"MOUSE_Fun_14"},
{"keyCode":"MOUSE_Fun_15","functionType":"MOUSE","value":"Rightbutton","hid":2,"translate":"Rightbutton","code":"MOUSE_Fun_15"},
{"keyCode":"MOUSE_Fun_16","functionType":"MOUSE","value":"Middlebutton","hid":3,"translate":"Middlebutton","code":"MOUSE_Fun_16"},
{"keyCode":"MOUSE_Fun_17","functionType":"MOUSE","value":"Forward","hid":5,"translate":"Forward","code":"MOUSE_Fun_17"},
{"keyCode":"MOUSE_Fun_18","functionType":"MOUSE","value":"Back","hid":4,"translate":"Back","code":"MOUSE_Fun_18"},
{"keyCode":"MOUSE_Fun_19","functionType":"MOUSE","value":"Scrollup","hid":6,"translate":"Scrollup","code":"MOUSE_Fun_19"},
{"keyCode":"MOUSE_Fun_20","functionType":"MOUSE","value":"Scrolldown","hid":7,"translate":"Scrolldown","code":"MOUSE_Fun_20"},
{"keyCode":"MOUSE_Fun_21","functionType":"MOUSE","value":"Profilecycleup","hid":1944,"translate":"Profilecycleup","code":"MOUSE_Fun_21"},
{"keyCode":"MOUSE_Fun_22","functionType":"MOUSE","value":"Profilecycledown","hid":1943,"translate":"Profilecycledown","code":"MOUSE_Fun_22"},
{"keyCode":"MOUSE_Fun_23","functionType":"MOUSE","value":"Batterystatuscheck","hid":1942,"translate":"Batterystatuscheck","code":"MOUSE_Fun_23"},
{"keyCode":"LaunchProgram","functionType":"LaunchProgram","value":"LaunchProgram","hid":1941,"translate":"LaunchProgram","code":"LaunchProgram"},
{"keyCode":"LaunchWebsite","functionType":"LaunchProgram","value":"LaunchWebsite","hid":1940,"translate":"LaunchWebsite","code":"LaunchWebsite"},
{"keyCode":"Shortcuts_Fun_25","functionType":"Shortcuts","value":"Email","hid":17,"translate":"Email","code":"Shortcuts_Fun_25"},
{"keyCode":"Shortcuts_Fun_26","functionType":"Shortcuts","value":"Calculator","hid":16,"translate":"Calculator","code":"Shortcuts_Fun_26"},
{"keyCode":"Shortcuts_Fun_27","functionType":"Shortcuts","value":"My Computer","hid":15,"translate":"My Computer","code":"Shortcuts_Fun_27"},
{"keyCode":"Shortcuts_Fun_28","functionType":"Shortcuts","value":"Explorer","hid":15,"translate":"Explorer","code":"Shortcuts_Fun_28"},
{"keyCode":"Shortcuts_Fun_29","functionType":"Shortcuts","value":"WWW Home","hid":8,"translate":"WWW Home","code":"Shortcuts_Fun_29"},
{"keyCode":"Shortcuts_Fun_30","functionType":"Shortcuts","value":"WWW Refresh","hid":9,"translate":"WWW Refresh","code":"Shortcuts_Fun_30"},
{"keyCode":"Shortcuts_Fun_31","functionType":"Shortcuts","value":"WWW Stop","hid":10,"translate":"WWW Stop","code":"Shortcuts_Fun_31"},
{"keyCode":"Shortcuts_Fun_32","functionType":"Shortcuts","value":"WWW Back","hid":11,"translate":"WWW Back","code":"Shortcuts_Fun_32"},
{"keyCode":"Shortcuts_Fun_33","functionType":"Shortcuts","value":"WWW Forward","hid":12,"translate":"WWW Forward","code":"Shortcuts_Fun_33"},
{"keyCode":"Shortcuts_Fun_34","functionType":"Shortcuts","value":"WWW Search","hid":14,"translate":"WWW Search","code":"Shortcuts_Fun_34"},
{"keyCode":"MacroFunction","functionType":"MacroFunction","value":"MacroFunction","hid":1923,"translate":"MacroFunction","code":"MacroFunction"},
{"keyCode":"ScrollWheel","functionType":"ScrollWheel","value":"Volume","hid":1922,"translate":"ScrollWheel","code":"ScrollWheel"},
{"keyCode":"Custom_Fnkey","functionType":"Custom_Fnkey","value":"FN","hid":"0x781","translate":"FN","code":"Custom_Fnkey"},
{"keyCode":"0","functionType":"Singlekey","value":"Left Click","hid":0xB0,"hid_ModelO:":0x01,"translate":"Left Click","code":"0"},
{"keyCode":"1","functionType":"Singlekey","value":"Scroll Click","hid":0xB2,"hid_ModelO:":0x03,"translate":"Scroll Click","code":"1"},
{"keyCode":"2","functionType":"Singlekey","value":"Right Click","hid":0xB1,"hid_ModelO:":0x02,"translate":"Right Click","code":"2"},
{"keyCode":"3","functionType":"Singlekey","value":"Back Key","hid": 0xB3,"hid_ModelO": 0x02, "translate":"Back Key","code":"3"},
{"keyCode":"4","functionType":"Singlekey","value":"Forward Key","hid": 0xB4,"hid_ModelO": 0x02,"translate":"Forward Key","code":"4"},
{"keyCode":"65","functionType":"Singlekey","value":"A","hid":0x04,"translate":"A","code":"KeyA"},
{"keyCode":"66","functionType":"Singlekey","value":"B","hid":0x05,"translate":"B","code":"KeyB"},
{"keyCode":"67","functionType":"Singlekey","value":"C","hid":0x06,"translate":"C","code":"KeyC"},
{"keyCode":"68","functionType":"Singlekey","value":"D","hid":0x07,"translate":"D","code":"KeyD"},
{"keyCode":"69","functionType":"Singlekey","value":"E","hid":0x08,"translate":"E","code":"KeyE"},
{"keyCode":"70","functionType":"Singlekey","value":"F","hid":0x09,"translate":"F","code":"KeyF"},
{"keyCode":"71","functionType":"Singlekey","value":"G","hid":0x0A,"translate":"G","code":"KeyG"},
{"keyCode":"72","functionType":"Singlekey","value":"H","hid":0x0B,"translate":"H","code":"KeyH"},
{"keyCode":"73","functionType":"Singlekey","value":"I","hid":0x0C,"translate":"I","code":"KeyI"},
{"keyCode":"74","functionType":"Singlekey","value":"J","hid":0x0D,"translate":"J","code":"KeyJ"},
{"keyCode":"75","functionType":"Singlekey","value":"K","hid":0x0E,"translate":"K","code":"KeyK"},
{"keyCode":"76","functionType":"Singlekey","value":"L","hid":0x0F,"translate":"L","code":"KeyL"},
{"keyCode":"77","functionType":"Singlekey","value":"M","hid":0x10,"translate":"M","code":"KeyM"},
{"keyCode":"78","functionType":"Singlekey","value":"N","hid":0x11,"translate":"N","code":"KeyN"},
{"keyCode":"79","functionType":"Singlekey","value":"O","hid":0x12,"translate":"O","code":"KeyO"},
{"keyCode":"80","functionType":"Singlekey","value":"P","hid":0x13,"translate":"P","code":"KeyP"},
{"keyCode":"81","functionType":"Singlekey","value":"Q","hid":0x14,"translate":"Q","code":"KeyQ"},
{"keyCode":"82","functionType":"Singlekey","value":"R","hid":0x15,"translate":"R","code":"KeyR"},
{"keyCode":"83","functionType":"Singlekey","value":"S","hid":0x16,"translate":"S","code":"KeyS"},
{"keyCode":"84","functionType":"Singlekey","value":"T","hid":0x17,"translate":"T","code":"KeyT"},
{"keyCode":"85","functionType":"Singlekey","value":"U","hid":0x18,"translate":"U","code":"KeyU"},
{"keyCode":"86","functionType":"Singlekey","value":"V","hid":0x19,"translate":"V","code":"KeyV"},
{"keyCode":"87","functionType":"Singlekey","value":"W","hid":0x1A,"translate":"W","code":"KeyW"},
{"keyCode":"88","functionType":"Singlekey","value":"X","hid":0x1B,"translate":"X","code":"KeyX"},
{"keyCode":"89","functionType":"Singlekey","value":"Y","hid":0x1C,"translate":"Y","code":"KeyY"},
{"keyCode":"90","functionType":"Singlekey","value":"Z","hid":0x1D,"translate":"Z","code":"KeyZ"},
{"keyCode":"48","functionType":"Singlekey","value":"0","hid":0x27,"translate":"0","code":"Digit0"},
{"keyCode":"49","functionType":"Singlekey","value":"1","hid":0x1E,"translate":"1","code":"Digit1"},
{"keyCode":"50","functionType":"Singlekey","value":"2","hid":0x1F,"translate":"2","code":"Digit2"},
{"keyCode":"51","functionType":"Singlekey","value":"3","hid":0x20,"translate":"3","code":"Digit3"},
{"keyCode":"52","functionType":"Singlekey","value":"4","hid":0x21,"translate":"4","code":"Digit4"},
{"keyCode":"53","functionType":"Singlekey","value":"5","hid":0x22,"translate":"5","code":"Digit5"},
{"keyCode":"54","functionType":"Singlekey","value":"6","hid":0x23,"translate":"6","code":"Digit6"},
{"keyCode":"55","functionType":"Singlekey","value":"7","hid":0x24,"translate":"7","code":"Digit7"},
{"keyCode":"56","functionType":"Singlekey","value":"8","hid":0x25,"translate":"8","code":"Digit8"},
{"keyCode":"57","functionType":"Singlekey","value":"9","hid":0x26,"translate":"9","code":"Digit9"},
{"keyCode":"8","functionType":"Singlekey","value":"Backspace","hid":42,"translate":"Backspace","code":"Backspace"},
{"keyCode":"9","functionType":"Singlekey","value":"Tab","hid":43,"translate":"Tab","code":"Tab"},
{"keyCode":"144","functionType":"Singlekey","value":"Num Lock","hid":83,"translate":"Num Lock","code":"NumLock"},
{"keyCode":"13","functionType":"Singlekey","value":"Enter","hid":40,"translate":"Enter","code":"Enter"},
{"keyCode":"16","functionType":"Singlekey","value":"Shift","hid":225,"translate":"Shift","code":"ShiftRight"},
{"keyCode":"16","functionType":"Singlekey","value":"Shift","hid":225,"translate":"Shift","code":"ShiftLeft"},
{"keyCode":"17","functionType":"Singlekey","value":"Ctrl","hid":224,"translate":"Ctrl","code":"ControlLeft"},
{"keyCode":"17","functionType":"Singlekey","value":"Ctrl","hid":224,"translate":"Ctrl","code":"ControlRight"},
{"keyCode":"18","functionType":"Singlekey","value":"Alt","hid":226,"translate":"Alt","code":"AltRight"},
{"keyCode":"18","functionType":"Singlekey","value":"Alt","hid":226,"translate":"Alt","code":"AltLeft"},
{"keyCode":"19","functionType":"Singlekey","value":"Break","hid":72,"translate":"Break","code":"Pause"},
{"keyCode":"20","functionType":"Singlekey","value":"CapsLock","hid":57,"translate":"CapsLock","code":"CapsLock"},
{"keyCode":"27","functionType":"Singlekey","value":"Esc","hid":41,"translate":"Esc","code":"Escape"},
{"keyCode":"32","functionType":"Singlekey","value":"Space","hid":44,"translate":"Space","code":"Space"},
{"keyCode":"33","functionType":"Singlekey","value":"PageUp","hid":75,"translate":"PageUp","code":"PageUp"},
{"keyCode":"34","functionType":"Singlekey","value":"PageDown","hid":78,"translate":"PageDown","code":"PageDown"},
{"keyCode":"35","functionType":"Singlekey","value":"End","hid":77,"translate":"End","code":"End"},
{"keyCode":"36","functionType":"Singlekey","value":"Home","hid":74,"translate":"Home","code":"Home"},
{"keyCode":"37","functionType":"Singlekey","value":"Left","hid":80,"translate":"Left","code":"ArrowLeft"},
{"keyCode":"38","functionType":"Singlekey","value":"Up","hid":82,"translate":"Up","code":"ArrowUp"},
{"keyCode":"39","functionType":"Singlekey","value":"Right","hid":79,"translate":"Right","code":"ArrowRight"},
{"keyCode":"40","functionType":"Singlekey","value":"Down","hid":81,"translate":"Down","code":"ArrowDown"},
{"keyCode":"44","functionType":"Singlekey","value":"PrintScreen","hid":"0x46","translate":"PrintScreen","code":"PrintScreen"},
{"keyCode":"45","functionType":"Singlekey","value":"Insert","hid":73,"translate":"Insert","code":"Insert"},
{"keyCode":"46","functionType":"Singlekey","value":"Delete","hid":76,"translate":"Delete","code":"Delete"},
{"keyCode":"91","functionType":"Singlekey","value":"Left Win","hid":227,"translate":"Left Win","code":"MetaLeft"},
{"keyCode":"92","functionType":"Singlekey","value":"Right Win","hid":231,"Modifier":0x80,"translate":"Right Win","code":"MetaRight"},
{"keyCode":"93","functionType":"Singlekey","value":"Menu","hid":101,"translate":"Menu","code":"ContextMenu"},
{"keyCode":"96","functionType":"Singlekey","value":"Numpad0","hid":0x62,"translate":"Numpad0","code":"Numpad0"},
{"keyCode":"97","functionType":"Singlekey","value":"Numpad1","hid":0x59,"translate":"Numpad1","code":"Numpad1"},
{"keyCode":"98","functionType":"Singlekey","value":"Numpad2","hid":0x5a,"translate":"Numpad2","code":"Numpad2"},
{"keyCode":"99","functionType":"Singlekey","value":"Numpad3","hid":0x5b,"translate":"Numpad3","code":"Numpad3"},
{"keyCode":"100","functionType":"Singlekey","value":"Numpad4","hid":0x5c,"translate":"Numpad4","code":"Numpad4"},
{"keyCode":"101","functionType":"Singlekey","value":"Numpad5","hid":0x5d,"translate":"Numpad5","code":"Numpad5"},
{"keyCode":"102","functionType":"Singlekey","value":"Numpad6","hid":0x5e,"translate":"Numpad6","code":"Numpad6"},
{"keyCode":"103","functionType":"Singlekey","value":"Numpad7","hid":0x5f,"translate":"Numpad7","code":"Numpad7"},
{"keyCode":"104","functionType":"Singlekey","value":"Numpad8","hid":0x60,"translate":"Numpad8","code":"Numpad8"},
{"keyCode":"105","functionType":"Singlekey","value":"Numpad9","hid":0x61,"translate":"Numpad9","code":"Numpad9"},
{"keyCode":"13","functionType":"Singlekey","value":"NumpadEnter","hid":0x58,"translate":"NumpadEnter","code":"NumpadEnter"},
{"keyCode":"106","functionType":"Singlekey","value":"*","hid":85,"translate":"*","code":"NumpadMultiply"},
{"keyCode":"107","functionType":"Singlekey","value":"+","hid":87,"translate":"+","code":"NumpadAdd"},
{"keyCode":"109","functionType":"Singlekey","value":"-","hid":86,"translate":"-","code":"NumpadSubtract"},
{"keyCode":"110","functionType":"Singlekey","value":".","hid":0x63,"translate":".","code":"NumpadDecimal"},
{"keyCode":"111","functionType":"Singlekey","value":"/","hid":84,"translate":"/","code":"NumpadDivide"},
{"keyCode":"112","functionType":"Singlekey","value":"F1","hid":0x3A,"translate":"F1","code":"F1"},
{"keyCode":"113","functionType":"Singlekey","value":"F2","hid":0x3B,"translate":"F2","code":"F2"},
{"keyCode":"114","functionType":"Singlekey","value":"F3","hid":0x3C,"translate":"F3","code":"F3"},
{"keyCode":"115","functionType":"Singlekey","value":"F4","hid":0x3D,"translate":"F4","code":"F4"},
{"keyCode":"116","functionType":"Singlekey","value":"F5","hid":0x3E,"translate":"F5","code":"F5"},
{"keyCode":"117","functionType":"Singlekey","value":"F6","hid":0x3F,"translate":"F6","code":"F6"},
{"keyCode":"118","functionType":"Singlekey","value":"F7","hid":0x40,"translate":"F7","code":"F7"},
{"keyCode":"119","functionType":"Singlekey","value":"F8","hid":0x41,"translate":"F8","code":"F8"},
{"keyCode":"120","functionType":"Singlekey","value":"F9","hid":0x42,"translate":"F9","code":"F9"},
{"keyCode":"121","functionType":"Singlekey","value":"F10","hid":0x43,"translate":"F10","code":"F10"},
{"keyCode":"122","functionType":"Singlekey","value":"F11","hid":0x44,"translate":"F11","code":"F11"},
{"keyCode":"123","functionType":"Singlekey","value":"F12","hid":0x45,"translate":"F12","code":"F12"},
{"keyCode":"145","functionType":"Singlekey","value":"Scroll Lock","hid":71,"translate":"Scroll Lock","code":"ScrollLock"},
{"keyCode":"186","functionType":"Singlekey","value":";","hid":51,"translate":";","code":"Semicolon"},
{"keyCode":"187","functionType":"Singlekey","value":"=","hid":46,"translate":"=","code":"Equal"},
{"keyCode":"188","functionType":"Singlekey","value":",","hid":54,"translate":",","code":"Comma"},
{"keyCode":"189","functionType":"Singlekey","value":"-","hid":45,"translate":"-","code":"Minus"},
{"keyCode":"190","functionType":"Singlekey","value":"dot","hid":55,"translate":"dot","code":"Period"},
{"keyCode":"191","functionType":"Singlekey","value":"/","hid":56,"translate":"/","code":"Slash"},
{"keyCode":"192","functionType":"Singlekey","value":"~","hid":53,"translate":"~","code":"Backquote"},
{"keyCode":"219","functionType":"Singlekey","value":"[","hid":47,"translate":"[","code":"BracketLeft"},
{"keyCode":"220","functionType":"Singlekey","value":"|","hid":49,"translate":"|","code":"Backslash"},
{"keyCode":"226","functionType":"Singlekey","value":"\\","hid":49,"translate":"IntlBackslash","code":"IntlBackslash"},
{"keyCode":"221","functionType":"Singlekey","value":"]","hid":48,"translate":"]","code":"BracketRight"},
{"keyCode":"222","functionType":"Singlekey","value":"'","hid":52,"translate":"'","code":"Quote"}]


exports.KeyMapping = KeyMapping
exports.MediaMapping = MediaMapping
exports.WindowsMapping = WindowsMapping
exports.AllFunctionMapping = AllFunctionMapping
exports.Shortcuts_WindowsMapping = Shortcuts_WindowsMapping
exports.SupportLanguage = SupportLanguage

function ProfileDefault() {
    var Profile_Info_Default = {
        //ProfileID:1,
        MousePerformance: {
            iStage: 1,
            iXYSync: 2,
            iPollingRate: 500,
            iCalibration: 1,
        },
        MouseLighting: {
            Amplitude: 2500,
            Angle: 1,
            bQuickEffect: false,
            ColorNumber: 5,
            Decay: 50,
            Fire: 5,
            iBrightness: 50,
            iEffect: 1,
            iSpeed: 50,
            Width: 3,
        },
        MouseBtnList: [
            { id: 1, group: 1, function: 1, name: 'Left button' },
            { id: 2, group: 1, function: 2, name: 'Right button' },
            { id: 3, group: 1, function: 3, name: 'Middle button' },
            { id: 4, group: 4, function: 1, name: 'Lighting effect switch' },
            { id: 5, group: 1, function: 10, name: 'DPI increase loop' },
            { id: 6, group: 1, function: 4, name: 'Forward button' },
            { id: 7, group: 1, function: 5, name: 'Backward button' },
            { id: 8, group: 1, function: 13, name: 'Squeeze' },
        ],
    }
    return Profile_Info_Default
}
exports.ProfileDefault = ProfileDefault

var CountryCode = [
    { code: 'AF', value: 'Afghanistan' },
    { code: 'AX', value: 'Åland Islands' },
    { code: 'AL', value: 'Albania' },
    { code: 'DZ', value: 'Algeria' },
    { code: 'AS', value: 'American Samoa' },
    { code: 'AD', value: 'Andorra' },
    { code: 'AO', value: 'Angola' },
    { code: 'AI', value: 'Anguilla' },
    { code: 'AQ', value: 'Antarctica' },
    { code: 'AG', value: 'Antigua and Barbuda' },
    { code: 'AR', value: 'Argentina' },
    { code: 'AM', value: 'Armenia' },
    { code: 'AW', value: 'Aruba' },
    { code: 'AU', value: 'Australia' },
    { code: 'AT', value: 'Austria' },
    { code: 'AZ', value: 'Azerbaijan' },
    { code: 'BS', value: 'Bahamas' },
    { code: 'BH', value: 'Bahrain' },
    { code: 'BD', value: 'Bangladesh' },
    { code: 'BB', value: 'Barbados' },
    { code: 'BY', value: 'Belarus' },
    { code: 'BE', value: 'Belgium' },
    { code: 'BZ', value: 'Belize' },
    { code: 'BJ', value: 'Benin' },
    { code: 'BM', value: 'Bermuda' },
    { code: 'BT', value: 'Bhutan' },
    { code: 'BO', value: 'Bolivia, Plurinational State of' },
    { code: 'BQ', value: 'Bonaire, Sint Eustatius and Saba' },
    { code: 'BA', value: 'Bosnia and Herzegovina' },
    { code: 'BW', value: 'Botswana' },
    { code: 'BV', value: 'Bouvet Island' },
    { code: 'BR', value: 'Brazil' },
    { code: 'IO', value: 'British Indian Ocean Territory' },
    { code: 'BN', value: 'Brunei Darussalam' },
    { code: 'BG', value: 'Bulgaria' },
    { code: 'BF', value: 'Burkina Faso' },
    { code: 'BI', value: 'Burundi' },
    { code: 'KH', value: 'Cambodia' },
    { code: 'CM', value: 'Cameroon' },
    { code: 'CA', value: 'Canada' },
    { code: 'CV', value: 'Cape Verde' },
    { code: 'KY', value: 'Cayman Islands' },
    { code: 'CF', value: 'Central African Republic' },
    { code: 'TD', value: 'Chad' },
    { code: 'CL', value: 'Chile' },
    { code: 'CN', value: 'China' },
    { code: 'CX', value: 'Christmas Island' },
    { code: 'CC', value: 'Cocos (Keeling) Islands' },
    { code: 'CO', value: 'Colombia' },
    { code: 'KM', value: 'Comoros' },
    { code: 'CG', value: 'Congo' },
    { code: 'CD', value: 'Congo, the Democratic Republic of the' },
    { code: 'CK', value: 'Cook Islands' },
    { code: 'CR', value: 'Costa Rica' },
    { code: 'CI', value: "Côte d'Ivoire" },
    { code: 'HR', value: 'Croatia' },
    { code: 'CU', value: 'Cuba' },
    { code: 'CW', value: 'Curaçao' },
    { code: 'CY', value: 'Cyprus' },
    { code: 'CZ', value: 'Czech Republic' },
    { code: 'DK', value: 'Denmark' },
    { code: 'DJ', value: 'Djibouti' },
    { code: 'DM', value: 'Dominica' },
    { code: 'DO', value: 'Dominican Republic' },
    { code: 'EC', value: 'Ecuador' },
    { code: 'EG', value: 'Egypt' },
    { code: 'SV', value: 'El Salvador' },
    { code: 'GQ', value: 'Equatorial Guinea' },
    { code: 'ER', value: 'Eritrea' },
    { code: 'EE', value: 'Estonia' },
    { code: 'ET', value: 'Ethiopia' },
    { code: 'FK', value: 'Falkland Islands (Malvinas)' },
    { code: 'FO', value: 'Faroe Islands' },
    { code: 'FJ', value: 'Fiji' },
    { code: 'FI', value: 'Finland' },
    { code: 'FR', value: 'France' },
    { code: 'GF', value: 'French Guiana' },
    { code: 'PF', value: 'French Polynesia' },
    { code: 'TF', value: 'French Southern Territories' },
    { code: 'GA', value: 'Gabon' },
    { code: 'GM', value: 'Gambia' },
    { code: 'GE', value: 'Georgia' },
    { code: 'DE', value: 'Germany' },
    { code: 'GH', value: 'Ghana' },
    { code: 'GI', value: 'Gibraltar' },
    { code: 'GR', value: 'Greece' },
    { code: 'GL', value: 'Greenland' },
    { code: 'GD', value: 'Grenada' },
    { code: 'GP', value: 'Guadeloupe' },
    { code: 'GU', value: 'Guam' },
    { code: 'GT', value: 'Guatemala' },
    { code: 'GG', value: 'Guernsey' },
    { code: 'GN', value: 'Guinea' },
    { code: 'GW', value: 'Guinea-Bissau' },
    { code: 'GY', value: 'Guyana' },
    { code: 'HT', value: 'Haiti' },
    { code: 'HM', value: 'Heard Island and McDonald Islands' },
    { code: 'VA', value: 'Holy See (Vatican City State)' },
    { code: 'HN', value: 'Honduras' },
    { code: 'HK', value: 'Hong Kong' },
    { code: 'HU', value: 'Hungary' },
    { code: 'IS', value: 'Iceland' },
    { code: 'IN', value: 'India' },
    { code: 'ID', value: 'Indonesia' },
    { code: 'IR', value: 'Iran, Islamic Republic of' },
    { code: 'IQ', value: 'Iraq' },
    { code: 'IE', value: 'Ireland' },
    { code: 'IM', value: 'Isle of Man' },
    { code: 'IL', value: 'Israel' },
    { code: 'IT', value: 'Italy' },
    { code: 'JM', value: 'Jamaica' },
    { code: 'JP', value: 'Japan' },
    { code: 'JE', value: 'Jersey' },
    { code: 'JO', value: 'Jordan' },
    { code: 'KZ', value: 'Kazakhstan' },
    { code: 'KE', value: 'Kenya' },
    { code: 'KI', value: 'Kiribati' },
    { code: 'KP', value: "Korea, Democratic People's Republic of" },
    { code: 'KR', value: 'Korea, Republic of' },
    { code: 'KW', value: 'Kuwait' },
    { code: 'KG', value: 'Kyrgyzstan' },
    { code: 'LA', value: "Lao People's Democratic Republic" },
    { code: 'LV', value: 'Latvia' },
    { code: 'LB', value: 'Lebanon' },
    { code: 'LS', value: 'Lesotho' },
    { code: 'LR', value: 'Liberia' },
    { code: 'LY', value: 'Libya' },
    { code: 'LI', value: 'Liechtenstein' },
    { code: 'LT', value: 'Lithuania' },
    { code: 'LU', value: 'Luxembourg' },
    { code: 'MO', value: 'Macao' },
    { code: 'MK', value: 'Macedonia, the former Yugoslav Republic of' },
    { code: 'MG', value: 'Madagascar' },
    { code: 'MW', value: 'Malawi' },
    { code: 'MY', value: 'Malaysia' },
    { code: 'MV', value: 'Maldives' },
    { code: 'ML', value: 'Mali' },
    { code: 'MT', value: 'Malta' },
    { code: 'MH', value: 'Marshall Islands' },
    { code: 'MQ', value: 'Martinique' },
    { code: 'MR', value: 'Mauritania' },
    { code: 'MU', value: 'Mauritius' },
    { code: 'YT', value: 'Mayotte' },
    { code: 'MX', value: 'Mexico' },
    { code: 'FM', value: 'Micronesia, Federated States of' },
    { code: 'MD', value: 'Moldova, Republic of' },
    { code: 'MC', value: 'Monaco' },
    { code: 'MN', value: 'Mongolia' },
    { code: 'ME', value: 'Montenegro' },
    { code: 'MS', value: 'Montserrat' },
    { code: 'MA', value: 'Morocco' },
    { code: 'MZ', value: 'Mozambique' },
    { code: 'MM', value: 'Myanmar' },
    { code: 'NA', value: 'Namibia' },
    { code: 'NR', value: 'Nauru' },
    { code: 'NP', value: 'Nepal' },
    { code: 'NL', value: 'Netherlands' },
    { code: 'NC', value: 'New Caledonia' },
    { code: 'NZ', value: 'New Zealand' },
    { code: 'NI', value: 'Nicaragua' },
    { code: 'NE', value: 'Niger' },
    { code: 'NG', value: 'Nigeria' },
    { code: 'NU', value: 'Niue' },
    { code: 'NF', value: 'Norfolk Island' },
    { code: 'MP', value: 'Northern Mariana Islands' },
    { code: 'NO', value: 'Norway' },
    { code: 'OM', value: 'Oman' },
    { code: 'PK', value: 'Pakistan' },
    { code: 'PW', value: 'Palau' },
    { code: 'PS', value: 'Palestinian Territory, Occupied' },
    { code: 'PA', value: 'Panama' },
    { code: 'PG', value: 'Papua New Guinea' },
    { code: 'PY', value: 'Paraguay' },
    { code: 'PE', value: 'Peru' },
    { code: 'PH', value: 'Philippines' },
    { code: 'PN', value: 'Pitcairn' },
    { code: 'PL', value: 'Poland' },
    { code: 'PT', value: 'Portugal' },
    { code: 'PR', value: 'Puerto Rico' },
    { code: 'QA', value: 'Qatar' },
    { code: 'RE', value: 'Réunion' },
    { code: 'RO', value: 'Romania' },
    { code: 'RU', value: 'Russian Federation' },
    { code: 'RW', value: 'Rwanda' },
    { code: 'BL', value: 'Saint Barthélemy' },
    { code: 'SH', value: 'Saint Helena, Ascension and Tristan da Cunha' },
    { code: 'KN', value: 'Saint Kitts and Nevis' },
    { code: 'LC', value: 'Saint Lucia' },
    { code: 'MF', value: 'Saint Martin (French part)' },
    { code: 'PM', value: 'Saint Pierre and Miquelon' },
    { code: 'VC', value: 'Saint Vincent and the Grenadines' },
    { code: 'WS', value: 'Samoa' },
    { code: 'SM', value: 'San Marino' },
    { code: 'ST', value: 'Sao Tome and Principe' },
    { code: 'SA', value: 'Saudi Arabia' },
    { code: 'SN', value: 'Senegal' },
    { code: 'RS', value: 'Serbia' },
    { code: 'SC', value: 'Seychelles' },
    { code: 'SL', value: 'Sierra Leone' },
    { code: 'SG', value: 'Singapore' },
    { code: 'SX', value: 'Sint Maarten (Dutch part)' },
    { code: 'SK', value: 'Slovakia' },
    { code: 'SI', value: 'Slovenia' },
    { code: 'SB', value: 'Solomon Islands' },
    { code: 'SO', value: 'Somalia' },
    { code: 'ZA', value: 'South Africa' },
    { code: 'GS', value: 'South Georgia and the South Sandwich Islands' },
    { code: 'SS', value: 'South Sudan' },
    { code: 'ES', value: 'Spain' },
    { code: 'LK', value: 'Sri Lanka' },
    { code: 'SD', value: 'Sudan' },
    { code: 'SR', value: 'Suriname' },
    { code: 'SJ', value: 'Svalbard and Jan Mayen' },
    { code: 'SZ', value: 'Swaziland' },
    { code: 'SE', value: 'Sweden' },
    { code: 'CH', value: 'Switzerland' },
    { code: 'SY', value: 'Syrian Arab Republic' },
    { code: 'TW', value: 'Taiwan, Province of China' },
    { code: 'TJ', value: 'Tajikistan' },
    { code: 'TZ', value: 'Tanzania, United Republic of' },
    { code: 'TH', value: 'Thailand' },
    { code: 'TL', value: 'Timor-Leste' },
    { code: 'TG', value: 'Togo' },
    { code: 'TK', value: 'Tokelau' },
    { code: 'TO', value: 'Tonga' },
    { code: 'TT', value: 'Trinidad and Tobago' },
    { code: 'TN', value: 'Tunisia' },
    { code: 'TR', value: 'Turkey' },
    { code: 'TM', value: 'Turkmenistan' },
    { code: 'TC', value: 'Turks and Caicos Islands' },
    { code: 'TV', value: 'Tuvalu' },
    { code: 'UG', value: 'Uganda' },
    { code: 'UA', value: 'Ukraine' },
    { code: 'AE', value: 'United Arab Emirates' },
    { code: 'GB', value: 'United Kingdom' },
    { code: 'US', value: 'United States' },
    { code: 'UM', value: 'United States Minor Outlying Islands' },
    { code: 'UY', value: 'Uruguay' },
    { code: 'UZ', value: 'Uzbekistan' },
    { code: 'VU', value: 'Vanuatu' },
    { code: 'VE', value: 'Venezuela, Bolivarian Republic of' },
    { code: 'VN', value: 'Viet Nam' },
    { code: 'VG', value: 'Virgin Islands, British' },
    { code: 'VI', value: 'Virgin Islands, U.S.' },
    { code: 'WF', value: 'Wallis and Futuna' },
    { code: 'EH', value: 'Western Sahara' },
    { code: 'YE', value: 'Yemen' },
    { code: 'ZM', value: 'Zambia' },
    { code: 'ZW', value: 'Zimbabwe' },
]

exports.CountryCode = CountryCode
